name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: df5596ae69f091a33400921c52118d57d8224e10

  logging:
    level: info

  peer:
    timeout:
      connection: 10s
      queryResponse: 45s
      executeTxResponse: 120s
  eventService:
    timeout:
      connection: 10s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 10s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:
  
  channel:
    orderers:
      
      - orderer-40766ef07f1a65997226a55a2cd3badb0506f02a-0.orderer-40766ef07f1a65997226a55a2cd3badb0506f02a.default.svc.cluster.local
      
    peers:
      
      peer-df5596ae69f091a33400921c52118d57d8224e10-0.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local:30605:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      
      peer-df5596ae69f091a33400921c52118d57d8224e10-1.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local:30606:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      
    chaincodes:
      - distribution:1.0
  
organizations:
  
  df5596ae69f091a33400921c52118d57d8224e10:
    mspid: df5596ae69f091a33400921c52118d57d8224e10MSP

    cryptoPath:  D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/df5596ae69f091a33400921c52118d57d8224e10.peer/msp
    tlsCryptoKeyPath: D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/df5596ae69f091a33400921c52118d57d8224e10.peer/tls/server.key
    tlsCryptoCertPath: D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/df5596ae69f091a33400921c52118d57d8224e10.peer/tls/server.crt

    peers:
      
      - peer-df5596ae69f091a33400921c52118d57d8224e10-0.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local:30605
      
      - peer-df5596ae69f091a33400921c52118d57d8224e10-1.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local:30606
      
    certificateAuthorities:
      - ca-org1
  
  ordererorg:
      mspID: "40766ef07f1a65997226a55a2cd3badb0506f02aMSP"

      cryptoPath: D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/40766ef07f1a65997226a55a2cd3badb0506f02a.orderer/msp
orderer-eip: 122.112.205.159
orderers:
  
  orderer-40766ef07f1a65997226a55a2cd3badb0506f02a-0.orderer-40766ef07f1a65997226a55a2cd3badb0506f02a.default.svc.cluster.local:
    url: grpcs://122.112.205.159:30805

    grpcOptions:
      ssl-target-name-override: orderer-40766ef07f1a65997226a55a2cd3badb0506f02a-0.orderer-40766ef07f1a65997226a55a2cd3badb0506f02a.default.svc.cluster.local
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/40766ef07f1a65997226a55a2cd3badb0506f02a.orderer/msp/tlscacerts/tlsca.40766ef07f1a65997226a55a2cd3badb0506f02a-cert.pem
  
peers:
  
  
  peer-df5596ae69f091a33400921c52118d57d8224e10-0.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local:30605:
  
    
    url: grpcs://122.112.205.159:30605
    
    grpcOptions:
      ssl-target-name-override: peer-df5596ae69f091a33400921c52118d57d8224e10-0.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/df5596ae69f091a33400921c52118d57d8224e10.peer/msp/tlscacerts/tlsca.df5596ae69f091a33400921c52118d57d8224e10-cert.pem
  
  
  peer-df5596ae69f091a33400921c52118d57d8224e10-1.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local:30606:
  
    
    url: grpcs://122.112.205.159:30606
    
    grpcOptions:
      ssl-target-name-override: peer-df5596ae69f091a33400921c52118d57d8224e10-1.peer-df5596ae69f091a33400921c52118d57d8224e10.default.svc.cluster.local
      grpc.http2.keepalive_time: 15

    tlsCACerts:
      path: D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/df5596ae69f091a33400921c52118d57d8224e10.peer/msp/tlscacerts/tlsca.df5596ae69f091a33400921c52118d57d8224e10-cert.pem
  
certificateAuthorities:
  ca-org1:
    url: http://139.9.120.244:7054
    httpOptions:
      verify: true
    tlsCACerts:
      path: D:/code/huawei/java/yxl-cloud-parent/yxl-blockchain/src/main/resources/config/df5596ae69f091a33400921c52118d57d8224e10.peer/msp/tlscacerts/tlsca.df5596ae69f091a33400921c52118d57d8224e10-cert.pem
#      path: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/ca_root.pem
#      client:
#       keyfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client-key.pem
#       certfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1